/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

//import gui.Transaction;
//import gui.Login;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
//import java.util.logging.Level; // Have different logging levels (severity) of log messages
import java.util.logging.Logger; // Create log messages (debugging purpose)
import javax.swing.JOptionPane;
import manager.UserManager;
import manager.TransactionManager;
//import database.GetTransaction;

/**
 * Dashboard screen for Budget Buddy.
 * @author Kong Kar Shin 
 * Responsibilities:
 * - Show today's date
 * - Show this month's totals: Net Cash Flow, Income, Expense
 * - Navigate to Transaction entry, History, and Logout
 */

public class Dashboard extends javax.swing.JFrame {
    
//    private static final GetTransaction trans = new GetTransaction();
    private static final Logger logger = Logger.getLogger(Dashboard.class.getName());
    public static Dashboard instance; // Used by other screens to trigger a refresh
    private final UserManager userManager; // Add UserManager instance

    
    /**
     * Creates new form Transaction
     */
    public Dashboard() {
        initComponents();
        pack(); // Make sure layout finishes calculating the size
        setLocationRelativeTo(null); // Center on screen
        updateDate();
        updateDashboard(); // Show $ 0.00 or current values on load
        instance = this; // Store the active instance
        userManager = UserManager.getInstance();
    }

    /** Called by other windows (Transaction/History) after they change data. */
    public static void refreshData() {
        if (instance != null) {
            instance.updateDashboard(); // reload UI from TransactionManager
        }
    }
    
    /** Show today's date in header. */
    private void updateDate() {
        LocalDate currentDate = LocalDate.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("EEEE, MMMM d, yyyy");
        jLabelDate.setText(currentDate.format(formatter));
    }
     
    /** Pull totals from TransactionManager and update labels. */
    private void updateDashboard() {
        // IMPORTANT: TransactionManager totals are sign-based:
        // - getTotalIncome(): sum of non-negative amounts
        // - getTotalExpense(): sum of |negative amounts| (returned as positive)
        // - getNetCashFlow(): signed sum of all
         
        double totalIncome = TransactionManager.getTotalIncome();
        double totalExpense = TransactionManager.getTotalExpense();
        double netCashFlow = TransactionManager.getNetCashFlow();

        String netCashFlowStr = String.format("%s$ %.2f",
                netCashFlow >= 0 ? "+" : "-",
                Math.abs(netCashFlow)
        );

        String incomeStr = String.format("+$ %.2f", totalIncome);
        String expenseStr = String.format("-$ %.2f", totalExpense);

        jLabelTotal.setText(netCashFlowStr);
        jLabelTotalIncome.setText(incomeStr);
        jLabelTotalExpense.setText(expenseStr);
    }
 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabelApp = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        iconRichCat1 = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        iconRichCat2 = new javax.swing.JLabel();
        jLabelDate = new javax.swing.JLabel();
        panelNetCashFlow = new javax.swing.JPanel();
        jLabelNetCashFlow = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jPanelIncome = new javax.swing.JPanel();
        jLabelIncome = new javax.swing.JLabel();
        jLabelTotalIncome = new javax.swing.JLabel();
        jPanelExpense = new javax.swing.JPanel();
        jLabelExpense = new javax.swing.JLabel();
        jLabelTotalExpense = new javax.swing.JLabel();
        jButtonEnter = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jButtonHistory = new javax.swing.JButton();

        jLabelApp.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        jLabelApp.setForeground(new java.awt.Color(255, 255, 204));
        jLabelApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelApp.setText("The Finance Tracker");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(231, 242, 242));
        jPanel1.setPreferredSize(new java.awt.Dimension(466, 700));

        jPanel2.setBackground(new java.awt.Color(191, 229, 229));

        iconRichCat1.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        iconRichCat1.setForeground(new java.awt.Color(255, 255, 204));
        iconRichCat1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconRichCat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Adobe Express - file (1).png"))); // NOI18N

        jLabelTitle.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(48, 136, 181));
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Budget Buddy");

        iconRichCat2.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        iconRichCat2.setForeground(new java.awt.Color(255, 255, 204));
        iconRichCat2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconRichCat2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Adobe Express - file (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(iconRichCat1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iconRichCat2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelTitle)
                        .addGap(8, 8, 8))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(iconRichCat1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(iconRichCat2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        iconRichCat1.getAccessibleContext().setAccessibleName("icon rich cat 1");
        jLabelTitle.getAccessibleContext().setAccessibleName("Title");
        iconRichCat2.getAccessibleContext().setAccessibleName("icon rich cat 2");

        jLabelDate.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabelDate.setForeground(new java.awt.Color(74, 132, 201));
        jLabelDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDate.setText("Date");

        panelNetCashFlow.setBackground(new java.awt.Color(255, 255, 255));
        panelNetCashFlow.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(102, 153, 255)));
        panelNetCashFlow.setPreferredSize(new java.awt.Dimension(315, 60));

        jLabelNetCashFlow.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabelNetCashFlow.setForeground(new java.awt.Color(74, 132, 201));
        jLabelNetCashFlow.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelNetCashFlow.setText("Net Cash Flow:");
        jLabelNetCashFlow.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelTotal.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabelTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTotal.setPreferredSize(new java.awt.Dimension(100, 30));

        javax.swing.GroupLayout panelNetCashFlowLayout = new javax.swing.GroupLayout(panelNetCashFlow);
        panelNetCashFlow.setLayout(panelNetCashFlowLayout);
        panelNetCashFlowLayout.setHorizontalGroup(
            panelNetCashFlowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNetCashFlowLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelNetCashFlow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        panelNetCashFlowLayout.setVerticalGroup(
            panelNetCashFlowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNetCashFlowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNetCashFlowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(jLabelNetCashFlow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanelIncome.setBackground(new java.awt.Color(255, 255, 255));
        jPanelIncome.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(102, 153, 255)));

        jLabelIncome.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabelIncome.setForeground(new java.awt.Color(74, 132, 201));
        jLabelIncome.setText("Total Income: ");

        jLabelTotalIncome.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTotalIncome.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabelTotalIncome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTotalIncome.setPreferredSize(new java.awt.Dimension(100, 30));

        javax.swing.GroupLayout jPanelIncomeLayout = new javax.swing.GroupLayout(jPanelIncome);
        jPanelIncome.setLayout(jPanelIncomeLayout);
        jPanelIncomeLayout.setHorizontalGroup(
            jPanelIncomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIncomeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelIncome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTotalIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanelIncomeLayout.setVerticalGroup(
            jPanelIncomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelIncomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelIncomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelTotalIncome, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jLabelIncome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanelExpense.setBackground(new java.awt.Color(255, 255, 255));
        jPanelExpense.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(102, 153, 255)));

        jLabelExpense.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabelExpense.setForeground(new java.awt.Color(74, 132, 201));
        jLabelExpense.setText("Total Expense: ");

        jLabelTotalExpense.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabelTotalExpense.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTotalExpense.setPreferredSize(new java.awt.Dimension(100, 30));

        javax.swing.GroupLayout jPanelExpenseLayout = new javax.swing.GroupLayout(jPanelExpense);
        jPanelExpense.setLayout(jPanelExpenseLayout);
        jPanelExpenseLayout.setHorizontalGroup(
            jPanelExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExpenseLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelExpense)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTotalExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanelExpenseLayout.setVerticalGroup(
            jPanelExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelExpenseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelTotalExpense, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jLabelExpense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jButtonEnter.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jButtonEnter.setForeground(new java.awt.Color(74, 132, 201));
        jButtonEnter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img.entericons.png"))); // NOI18N
        jButtonEnter.setText("Enter");
        jButtonEnter.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonEnter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEnterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonEnterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonEnterMouseExited(evt);
            }
        });
        jButtonEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnterActionPerformed(evt);
            }
        });

        jButtonLogout.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jButtonLogout.setForeground(new java.awt.Color(74, 132, 201));
        jButtonLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img.logouticons.png"))); // NOI18N
        jButtonLogout.setText("Logout");
        jButtonLogout.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonLogoutMouseExited(evt);
            }
        });
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        jButtonHistory.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jButtonHistory.setForeground(new java.awt.Color(74, 132, 201));
        jButtonHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img.historyicons.png"))); // NOI18N
        jButtonHistory.setText("History");
        jButtonHistory.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonHistoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonHistoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonHistoryMouseExited(evt);
            }
        });
        jButtonHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jButtonEnter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(107, 107, 107))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelIncome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelNetCashFlow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                            .addComponent(jPanelExpense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabelDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(panelNetCashFlow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jPanelIncome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jPanelExpense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButtonEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButtonHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 35;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEnterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEnterMouseClicked
        Transaction transactionPage = new Transaction();
        transactionPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonEnterMouseClicked

    private void jButtonEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEnterActionPerformed

    private void jButtonLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLogoutMouseClicked
        // TODO add your handling code here:
        userManager.logout();
        JOptionPane.showMessageDialog(this, "User logged out successfully!");
        
        Login loginPage = new Login();
        loginPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonLogoutMouseClicked

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jButtonHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHistoryMouseClicked
        History historyPage = new History();
        historyPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonHistoryMouseClicked

    private void jButtonHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHistoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHistoryActionPerformed

    private void jButtonEnterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEnterMouseEntered
        // TODO add your handling code here:
        jButtonEnter.setBackground(new java.awt.Color(102, 102, 255));
        jButtonEnter.setForeground(new java.awt.Color(0,0,204));
    }//GEN-LAST:event_jButtonEnterMouseEntered

    private void jButtonEnterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEnterMouseExited
        // TODO add your handling code here:
        jButtonEnter.setBackground(new java.awt.Color(255, 204, 204));
        jButtonEnter.setForeground(new java.awt.Color(74,132,201));
    }//GEN-LAST:event_jButtonEnterMouseExited

    private void jButtonHistoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHistoryMouseEntered
        // TODO add your handling code here:
        jButtonHistory.setBackground(new java.awt.Color(102, 102, 255));
        jButtonHistory.setForeground(new java.awt.Color(0,0,204));
    }//GEN-LAST:event_jButtonHistoryMouseEntered

    private void jButtonHistoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHistoryMouseExited
        // TODO add your handling code here:
        jButtonHistory.setBackground(new java.awt.Color(255, 204, 204));
        jButtonHistory.setForeground(new java.awt.Color(74,132,201));
    }//GEN-LAST:event_jButtonHistoryMouseExited

    private void jButtonLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLogoutMouseEntered
        // TODO add your handling code here:
        jButtonLogout.setBackground(new java.awt.Color(102, 102, 255));
        jButtonLogout.setForeground(new java.awt.Color(0,0,204));
    }//GEN-LAST:event_jButtonLogoutMouseEntered

    private void jButtonLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLogoutMouseExited
        // TODO add your handling code here:
        jButtonLogout.setBackground(new java.awt.Color(255, 204, 204));
        jButtonLogout.setForeground(new java.awt.Color(74,132,201));
    }//GEN-LAST:event_jButtonLogoutMouseExited

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconRichCat1;
    private javax.swing.JLabel iconRichCat2;
    private javax.swing.JButton jButtonEnter;
    private javax.swing.JButton jButtonHistory;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JLabel jLabelApp;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelExpense;
    private javax.swing.JLabel jLabelIncome;
    private javax.swing.JLabel jLabelNetCashFlow;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JLabel jLabelTotalExpense;
    private javax.swing.JLabel jLabelTotalIncome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelExpense;
    private javax.swing.JPanel jPanelIncome;
    private javax.swing.JPanel panelNetCashFlow;
    // End of variables declaration//GEN-END:variables
}
