/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * Forgot Password screen for Budget Buddy.
 * @author Kong Kar Shin
 * Responsibilities:
 * - Allows users to change their password by verifying their answers to the security question
 */
package gui;

import manager.UserManager;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;

public class ForgotPassword extends javax.swing.JFrame {
    
    private static final Logger logger = Logger.getLogger(ForgotPassword.class.getName());
    private final UserManager userManager;
    
    /**
     * Creates new form ForgotPassword
     */
    public ForgotPassword() {
        initComponents();
        pack(); // Make sure layout finishes calculating the size
        setLocationRelativeTo(null); // Center on screen
        userManager = UserManager.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jPanelMain = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        iconRichCat1 = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        iconRichCat2 = new javax.swing.JLabel();
        jLabelForgotPassword = new javax.swing.JLabel();
        jLabelUserName = new javax.swing.JLabel();
        jTextFieldUserName = new javax.swing.JTextField();
        jLabelSecurityQues = new javax.swing.JLabel();
        jComboBoxSecurityQues = new javax.swing.JComboBox<>();
        jLabelAnswer = new javax.swing.JLabel();
        jTextFieldSecurityAnswer = new javax.swing.JTextField();
        jLabelNewPass = new javax.swing.JLabel();
        jPasswordFieldNew = new javax.swing.JPasswordField();
        jLabelConfirmPass = new javax.swing.JLabel();
        jPasswordFieldConfirm = new javax.swing.JPasswordField();
        jButtonResetPassword = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("The Finance Tracker");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanelMain.setBackground(new java.awt.Color(231, 242, 242));
        jPanelMain.setPreferredSize(new java.awt.Dimension(450, 700));

        jPanel1.setBackground(new java.awt.Color(191, 229, 229));
        jPanel1.setPreferredSize(new java.awt.Dimension(450, 72));

        iconRichCat1.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        iconRichCat1.setForeground(new java.awt.Color(255, 255, 204));
        iconRichCat1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconRichCat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Adobe Express - file (1).png"))); // NOI18N

        jLabelTitle.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(48, 136, 181));
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Budget Buddy");

        iconRichCat2.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        iconRichCat2.setForeground(new java.awt.Color(255, 255, 204));
        iconRichCat2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconRichCat2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Adobe Express - file (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconRichCat1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iconRichCat2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelTitle)
                        .addGap(8, 8, 8))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(iconRichCat1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(iconRichCat2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        iconRichCat1.getAccessibleContext().setAccessibleName("icon rich cat 1");
        jLabelTitle.getAccessibleContext().setAccessibleName("Title");
        iconRichCat2.getAccessibleContext().setAccessibleName("icon rich cat 2");

        jLabelForgotPassword.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabelForgotPassword.setForeground(new java.awt.Color(74, 132, 201));
        jLabelForgotPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelForgotPassword.setText("Forget Password");
        jLabelForgotPassword.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelUserName.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabelUserName.setForeground(new java.awt.Color(74, 132, 201));
        jLabelUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUserName.setText("Username");
        jLabelUserName.setFocusable(false);
        jLabelUserName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTextFieldUserName.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jTextFieldUserName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldUserName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldUserName.setPreferredSize(new java.awt.Dimension(60, 22));
        jTextFieldUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUserNameActionPerformed(evt);
            }
        });

        jLabelSecurityQues.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabelSecurityQues.setForeground(new java.awt.Color(74, 132, 201));
        jLabelSecurityQues.setText("Choose your security question");

        jComboBoxSecurityQues.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jComboBoxSecurityQues.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is your favorite color?", "What is your favorite movie quote?", "What was the name of your first pet?", "What was your dream job as a child?", "What was your childhood nickname?" }));
        jComboBoxSecurityQues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSecurityQuesActionPerformed(evt);
            }
        });

        jLabelAnswer.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabelAnswer.setForeground(new java.awt.Color(74, 132, 201));
        jLabelAnswer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAnswer.setText("Your Answer");
        jLabelAnswer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTextFieldSecurityAnswer.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jTextFieldSecurityAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSecurityAnswerActionPerformed(evt);
            }
        });

        jLabelNewPass.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabelNewPass.setForeground(new java.awt.Color(74, 132, 201));
        jLabelNewPass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNewPass.setText("New password");
        jLabelNewPass.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPasswordFieldNew.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jPasswordFieldNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldNewActionPerformed(evt);
            }
        });

        jLabelConfirmPass.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabelConfirmPass.setForeground(new java.awt.Color(74, 132, 201));
        jLabelConfirmPass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelConfirmPass.setText("Confirm password");
        jLabelConfirmPass.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPasswordFieldConfirm.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jPasswordFieldConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldConfirmActionPerformed(evt);
            }
        });

        jButtonResetPassword.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jButtonResetPassword.setForeground(new java.awt.Color(74, 132, 201));
        jButtonResetPassword.setText("Reset Password");
        jButtonResetPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonResetPasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonResetPasswordMouseExited(evt);
            }
        });
        jButtonResetPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetPasswordActionPerformed(evt);
            }
        });

        jButtonBack.setBackground(new java.awt.Color(231, 242, 242));
        jButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img.backicons.png"))); // NOI18N
        jButtonBack.setBorder(null);
        jButtonBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonBackMouseExited(evt);
            }
        });
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelForgotPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelUserName)
                            .addComponent(jLabelSecurityQues)
                            .addComponent(jComboBoxSecurityQues, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAnswer)
                            .addComponent(jTextFieldSecurityAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNewPass)
                            .addComponent(jPasswordFieldNew, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelConfirmPass)
                            .addComponent(jPasswordFieldConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonResetPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelForgotPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addComponent(jLabelUserName)
                .addGap(5, 5, 5)
                .addComponent(jTextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelSecurityQues)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxSecurityQues, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelAnswer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldSecurityAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelNewPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordFieldNew, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabelConfirmPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordFieldConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jButtonResetPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -4;
        gridBagConstraints.ipady = -4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanelMain, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Check username and show security question
    private void checkUsername(){
        String username = jTextFieldUserName.getText();
        if (username.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter username");
            return; // Stop method
        }
        
        String securityQuestion = userManager.getSecurityQuestion(username);
        if (securityQuestion != null){
            // Set the security question in combo box
            jComboBoxSecurityQues.setSelectedItem(securityQuestion); // Show in the combo box
            jComboBoxSecurityQues.setEnabled(false); // Disable changing the question
        } else {
            JOptionPane.showMessageDialog(this, "Username not found");
        }
    }
    
    private void jTextFieldUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUserNameActionPerformed
        // Check username when user press Enter
        checkUsername();
    }//GEN-LAST:event_jTextFieldUserNameActionPerformed

    private void jComboBoxSecurityQuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSecurityQuesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSecurityQuesActionPerformed

    private void jTextFieldSecurityAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSecurityAnswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSecurityAnswerActionPerformed

    private void jPasswordFieldNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldNewActionPerformed

    private void jPasswordFieldConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldConfirmActionPerformed
    
    private void jButtonResetPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetPasswordActionPerformed
        try {
            String username = jTextFieldUserName.getText();
            String securityAnswer = jTextFieldSecurityAnswer.getText();
            String newPassword = new String(jPasswordFieldNew.getPassword());
            String confirmPassword = new String(jPasswordFieldConfirm.getPassword());

            // Validate inputs
            if (username.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter username");
                return;
            }
            if (securityAnswer.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter security answer");
                return;
            }
            if (newPassword.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter new password");
                return;
            }
            if (!newPassword.equals(confirmPassword)) {
                JOptionPane.showMessageDialog(this, "Passwords do not match");
                return;
            }

            // Try to reset password
            String result = userManager.resetPassword(username, securityAnswer, newPassword);

            if (result.equals("Password reset successful")) {
                JOptionPane.showMessageDialog(this, "Password reset successful!");
                // Return to login screen
                Login loginForm = new Login();
                loginForm.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, result, "Reset Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            logger.log(Level.SEVERE, "Error during password reset", e);
            JOptionPane.showMessageDialog(this, "An error occurred during password reset");
        }
    }//GEN-LAST:event_jButtonResetPasswordActionPerformed
                        
    private void jButtonBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBackMouseClicked
        Login loginForm = new Login();
        loginForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonBackMouseClicked

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonResetPasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonResetPasswordMouseEntered
        // TODO add your handling code here:
        jButtonResetPassword.setBackground(new java.awt.Color(102, 102, 255));
        jButtonResetPassword.setForeground(new java.awt.Color(0,0,204));
    }//GEN-LAST:event_jButtonResetPasswordMouseEntered

    private void jButtonResetPasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonResetPasswordMouseExited
        // TODO add your handling code here:
        jButtonResetPassword.setBackground(new java.awt.Color(255, 255, 255));
        jButtonResetPassword.setForeground(new java.awt.Color(74,132,201));
    }//GEN-LAST:event_jButtonResetPasswordMouseExited

    private void jButtonBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBackMouseEntered
        // TODO add your handling code here:
        jButtonBack.setBackground(new java.awt.Color(102, 102, 255));
        jButtonBack.setForeground(new java.awt.Color(0,0,204));
    }//GEN-LAST:event_jButtonBackMouseEntered

    private void jButtonBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBackMouseExited
        // TODO add your handling code here:
        jButtonBack.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBack.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_jButtonBackMouseExited

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new ForgotPassword().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconRichCat1;
    private javax.swing.JLabel iconRichCat2;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonResetPassword;
    private javax.swing.JComboBox<String> jComboBoxSecurityQues;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAnswer;
    private javax.swing.JLabel jLabelConfirmPass;
    private javax.swing.JLabel jLabelForgotPassword;
    private javax.swing.JLabel jLabelNewPass;
    private javax.swing.JLabel jLabelSecurityQues;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPasswordField jPasswordFieldConfirm;
    private javax.swing.JPasswordField jPasswordFieldNew;
    private javax.swing.JTextField jTextFieldSecurityAnswer;
    private javax.swing.JTextField jTextFieldUserName;
    // End of variables declaration//GEN-END:variables
}