/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * Login screen for Budget Buddy.
 * @author Kong Kar Shin
 * Responsibilities:
 * - Allows users to sign in with their credentials
 * - Has 2 buttons: Forgot Password? and Register here
 */
package gui;

import manager.UserManager;
import javax.swing.JOptionPane; // Pop up a standard dialog box
import java.util.logging.Level; // Have different logging levels (severity) of log messages
import java.util.logging.Logger; // Create log messages (debugging purpose)
import manager.TransactionManager;

public class Login extends javax.swing.JFrame {
    
    private static final Logger logger = Logger.getLogger(Login.class.getName());
    private final UserManager userManager; // Add UserManager instance

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        pack(); // Make sure layout finishes calculating the size
        setLocationRelativeTo(null); // Center on screen
        userManager = UserManager.getInstance(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabelApp = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        iconRichCat1 = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        iconRichCat2 = new javax.swing.JLabel();
        jLabelWelcome = new javax.swing.JLabel();
        jLabelSignIn = new javax.swing.JLabel();
        jTextFieldUserName = new javax.swing.JTextField();
        iconUser = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        iconPassword = new javax.swing.JLabel();
        jButtonSignIn = new javax.swing.JButton();
        jButtonForgotPassword = new javax.swing.JButton();
        jLabelnoACC = new javax.swing.JLabel();
        jLabelRegisterHere = new javax.swing.JLabel();

        jLabelApp.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        jLabelApp.setForeground(new java.awt.Color(255, 255, 204));
        jLabelApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelApp.setText("The Finance Tracker");
        jLabelApp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelApp.setPreferredSize(new java.awt.Dimension(400, 32));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(231, 242, 242));
        jPanel1.setPreferredSize(new java.awt.Dimension(450, 700));

        jPanel2.setBackground(new java.awt.Color(191, 229, 229));
        jPanel2.setPreferredSize(new java.awt.Dimension(450, 72));

        iconRichCat1.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        iconRichCat1.setForeground(new java.awt.Color(255, 255, 204));
        iconRichCat1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconRichCat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Adobe Express - file (1).png"))); // NOI18N

        jLabelTitle.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(48, 136, 181));
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Budget Buddy");

        iconRichCat2.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        iconRichCat2.setForeground(new java.awt.Color(255, 255, 204));
        iconRichCat2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconRichCat2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Adobe Express - file (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(iconRichCat1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iconRichCat2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelTitle)
                        .addGap(8, 8, 8))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(iconRichCat1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(iconRichCat2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        iconRichCat1.getAccessibleContext().setAccessibleName("icon rich cat 1");
        jLabelTitle.getAccessibleContext().setAccessibleName("Title");
        iconRichCat2.getAccessibleContext().setAccessibleName("icon rich cat 2");

        jLabelWelcome.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabelWelcome.setForeground(new java.awt.Color(74, 132, 201));
        jLabelWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWelcome.setText("WELCOME BACK :)");
        jLabelWelcome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelSignIn.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabelSignIn.setForeground(new java.awt.Color(74, 132, 201));
        jLabelSignIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSignIn.setText("Login");
        jLabelSignIn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTextFieldUserName.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextFieldUserName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldUserName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUserNameActionPerformed(evt);
            }
        });

        iconUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img.usernameicons.png"))); // NOI18N
        iconUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPasswordField.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });

        iconPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img.passwordicons.png"))); // NOI18N
        iconPassword.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButtonSignIn.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jButtonSignIn.setForeground(new java.awt.Color(74, 132, 201));
        jButtonSignIn.setText("Sign In");
        jButtonSignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonSignInMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonSignInMouseExited(evt);
            }
        });
        jButtonSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSignInActionPerformed(evt);
            }
        });

        jButtonForgotPassword.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jButtonForgotPassword.setForeground(new java.awt.Color(74, 132, 201));
        jButtonForgotPassword.setText("Forgot Password?");
        jButtonForgotPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonForgotPasswordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonForgotPasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonForgotPasswordMouseExited(evt);
            }
        });
        jButtonForgotPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonForgotPasswordActionPerformed(evt);
            }
        });

        jLabelnoACC.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabelnoACC.setForeground(new java.awt.Color(74, 132, 201));
        jLabelnoACC.setText("Don't have an account?");

        jLabelRegisterHere.setFont(new java.awt.Font("DialogInput", 3, 14)); // NOI18N
        jLabelRegisterHere.setForeground(new java.awt.Color(255, 0, 0));
        jLabelRegisterHere.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRegisterHere.setText("Register here");
        jLabelRegisterHere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegisterHereMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelRegisterHereMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelRegisterHereMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabelWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelSignIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelnoACC)
                    .addComponent(jLabelRegisterHere)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(iconUser)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(iconPassword)
                                .addGap(18, 18, 18)
                                .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonSignIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonForgotPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jLabelWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabelSignIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconUser))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconPassword))
                .addGap(54, 54, 54)
                .addComponent(jButtonSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonForgotPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabelnoACC, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelRegisterHere, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUserNameActionPerformed

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldActionPerformed

    private void jButtonSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSignInActionPerformed
        try {
            // Get username and password from fields
            String username = jTextFieldUserName.getText();
            String password = new String(jPasswordField.getPassword());

            // Attempt login
            String loginResult = userManager.login(username, password);

            if (loginResult.equals("Login successful")){
                // Show success message * this: current window
                JOptionPane.showMessageDialog(this, "Login successful!");
                
                TransactionManager.loadTransactionFromDB(username);
                
                Dashboard dashboardPage = new Dashboard();
                dashboardPage.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, loginResult, "Login Error", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (Exception e) {
            logger.log(Level.SEVERE, "Error during login", e);
            JOptionPane.showMessageDialog(this, "An error occurred during login");
        }
    }//GEN-LAST:event_jButtonSignInActionPerformed

    private void jButtonForgotPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonForgotPasswordMouseClicked
        ForgotPassword forgot = new ForgotPassword();
        forgot.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonForgotPasswordMouseClicked

    private void jButtonForgotPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonForgotPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonForgotPasswordActionPerformed

    private void jLabelRegisterHereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegisterHereMouseClicked
        Register registerForm = new Register();
        registerForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelRegisterHereMouseClicked

    private void jButtonSignInMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSignInMouseExited
        // TODO add your handling code here:
        jButtonSignIn.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSignIn.setForeground(new java.awt.Color(74,132,201));
    }//GEN-LAST:event_jButtonSignInMouseExited

    private void jButtonSignInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSignInMouseEntered
        // TODO add your handling code here:
        jButtonSignIn.setBackground(new java.awt.Color(102, 102, 255));
        jButtonSignIn.setForeground(new java.awt.Color(0,0,204));
    }//GEN-LAST:event_jButtonSignInMouseEntered

    private void jButtonForgotPasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonForgotPasswordMouseEntered
        // TODO add your handling code here:
        jButtonForgotPassword.setBackground(new java.awt.Color(102, 102, 255));
        jButtonForgotPassword.setForeground(new java.awt.Color(0,0,204));
    }//GEN-LAST:event_jButtonForgotPasswordMouseEntered

    private void jButtonForgotPasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonForgotPasswordMouseExited
        // TODO add your handling code here:
        jButtonForgotPassword.setBackground(new java.awt.Color(255, 255, 255));
        jButtonForgotPassword.setForeground(new java.awt.Color(74,132,201));
    }//GEN-LAST:event_jButtonForgotPasswordMouseExited

    private void jLabelRegisterHereMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegisterHereMouseEntered
        // TODO add your handling code here:
        jLabelRegisterHere.setForeground(new java.awt.Color(0,0,204));
    }//GEN-LAST:event_jLabelRegisterHereMouseEntered

    private void jLabelRegisterHereMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegisterHereMouseExited
        // TODO add your handling code here:
        jLabelRegisterHere.setForeground(new java.awt.Color(255,0,0));
    }//GEN-LAST:event_jLabelRegisterHereMouseExited

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconPassword;
    private javax.swing.JLabel iconRichCat1;
    private javax.swing.JLabel iconRichCat2;
    private javax.swing.JLabel iconUser;
    private javax.swing.JButton jButtonForgotPassword;
    private javax.swing.JButton jButtonSignIn;
    private javax.swing.JLabel jLabelApp;
    private javax.swing.JLabel jLabelRegisterHere;
    private javax.swing.JLabel jLabelSignIn;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelWelcome;
    private javax.swing.JLabel jLabelnoACC;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldUserName;
    // End of variables declaration//GEN-END:variables
}
