/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * Registration screen for Budget Buddy.
 * @author Kong Kar Shin
 * Responsibilities:
 * - Collect new user credentials + security question/answer
 * - Delegate creation to UserManager
 * - Navigate back to Login on success
 */
package gui;

import manager.UserManager;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Register extends javax.swing.JFrame {
    
    private static final Logger logger = Logger.getLogger(Register.class.getName());
    private final UserManager userManager;

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        pack(); // Make sure layout finishes calculating the size
        setLocationRelativeTo(null); // Center on screen
        userManager = UserManager.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabelApp1 = new javax.swing.JLabel();
        jPanelMain = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        iconRichCat2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelSignUp = new javax.swing.JLabel();
        jLabelUserName = new javax.swing.JLabel();
        jTextFieldUserName = new javax.swing.JTextField();
        jLabelPassword = new javax.swing.JLabel();
        jPasswordFieldCreate = new javax.swing.JPasswordField();
        jLabelConfirmPass = new javax.swing.JLabel();
        jPasswordFieldConfirm = new javax.swing.JPasswordField();
        jLabelSecurityQues = new javax.swing.JLabel();
        jComboBoxSecurityQues = new javax.swing.JComboBox<>();
        jLabelAnswer = new javax.swing.JLabel();
        jTextFieldAnswer = new javax.swing.JTextField();
        jButtonCreateACC = new javax.swing.JButton();
        jLabelBack = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        iconRichCat1 = new javax.swing.JLabel();

        jLabelApp1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabelApp1.setForeground(new java.awt.Color(48, 136, 181));
        jLabelApp1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelApp1.setText("(,,^v^,,)");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(460, 720));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanelMain.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMain.setPreferredSize(new java.awt.Dimension(450, 700));

        jPanel1.setBackground(new java.awt.Color(191, 229, 229));
        jPanel1.setInheritsPopupMenu(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(446, 700));

        iconRichCat2.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        iconRichCat2.setForeground(new java.awt.Color(255, 255, 204));
        iconRichCat2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconRichCat2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Adobe Express - file (1).png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(231, 242, 242));
        jPanel2.setPreferredSize(new java.awt.Dimension(446, 720));

        jLabelSignUp.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabelSignUp.setForeground(new java.awt.Color(74, 132, 201));
        jLabelSignUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSignUp.setText("Sign Up");
        jLabelSignUp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelUserName.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabelUserName.setForeground(new java.awt.Color(74, 132, 201));
        jLabelUserName.setText("Username");

        jTextFieldUserName.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jTextFieldUserName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldUserName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUserNameActionPerformed(evt);
            }
        });

        jLabelPassword.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabelPassword.setForeground(new java.awt.Color(74, 132, 201));
        jLabelPassword.setText("Password");

        jPasswordFieldCreate.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jPasswordFieldCreate.setToolTipText("");
        jPasswordFieldCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldCreateActionPerformed(evt);
            }
        });

        jLabelConfirmPass.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabelConfirmPass.setForeground(new java.awt.Color(74, 132, 201));
        jLabelConfirmPass.setText("Confirm Password");

        jPasswordFieldConfirm.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jPasswordFieldConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldConfirmActionPerformed(evt);
            }
        });

        jLabelSecurityQues.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabelSecurityQues.setForeground(new java.awt.Color(74, 132, 201));
        jLabelSecurityQues.setText("Security Question");

        jComboBoxSecurityQues.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jComboBoxSecurityQues.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is your favorite color?", "What is your favorite movie quote?", "What was the name of your first pet?", "What was your dream job as a child?", "What was your childhood nickname?" }));
        jComboBoxSecurityQues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSecurityQuesActionPerformed(evt);
            }
        });

        jLabelAnswer.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabelAnswer.setForeground(new java.awt.Color(74, 132, 201));
        jLabelAnswer.setText("Your Answer");

        jTextFieldAnswer.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jTextFieldAnswer.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAnswerActionPerformed(evt);
            }
        });

        jButtonCreateACC.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jButtonCreateACC.setForeground(new java.awt.Color(74, 132, 201));
        jButtonCreateACC.setText("Create account");
        jButtonCreateACC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonCreateACCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonCreateACCMouseExited(evt);
            }
        });
        jButtonCreateACC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateACCActionPerformed(evt);
            }
        });

        jLabelBack.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabelBack.setForeground(new java.awt.Color(255, 0, 0));
        jLabelBack.setText("Back to Sign In");
        jLabelBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBackMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelAnswer)
                                    .addComponent(jLabelSecurityQues)
                                    .addComponent(jLabelConfirmPass)
                                    .addComponent(jLabelPassword)
                                    .addComponent(jLabelUserName))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextFieldUserName)
                            .addComponent(jPasswordFieldCreate)
                            .addComponent(jPasswordFieldConfirm)
                            .addComponent(jTextFieldAnswer)
                            .addComponent(jComboBoxSecurityQues, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCreateACC)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabelBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(8, 8, 8)))))
                .addGap(48, 48, 48))
            .addComponent(jLabelSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabelSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabelUserName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordFieldCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelConfirmPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordFieldConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelSecurityQues)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxSecurityQues, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelAnswer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jButtonCreateACC)
                .addGap(18, 18, 18)
                .addComponent(jLabelBack, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addGap(46, 46, 46))
        );

        jLabelTitle.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(48, 136, 181));
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Budget Buddy");

        iconRichCat1.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        iconRichCat1.setForeground(new java.awt.Color(255, 255, 204));
        iconRichCat1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconRichCat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Adobe Express - file (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(iconRichCat1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iconRichCat2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitle)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(iconRichCat1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(iconRichCat2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        iconRichCat2.getAccessibleContext().setAccessibleName("icon rich cat 2");
        jLabelTitle.getAccessibleContext().setAccessibleName("Title");
        iconRichCat1.getAccessibleContext().setAccessibleName("icon rich cat 1");

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = -63;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 10, 32, 10);
        getContentPane().add(jPanelMain, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUserNameActionPerformed

    private void jPasswordFieldCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldCreateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldCreateActionPerformed

    private void jPasswordFieldConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldConfirmActionPerformed

    private void jComboBoxSecurityQuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSecurityQuesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSecurityQuesActionPerformed

    private void jTextFieldAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAnswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAnswerActionPerformed

    private void jButtonCreateACCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateACCActionPerformed
        try {
            // Get values from fields
            String username = jTextFieldUserName.getText();
            String password = new String(jPasswordFieldCreate.getPassword());
            String confirmPassword = new String(jPasswordFieldConfirm.getPassword());
            String securityQuestion = jComboBoxSecurityQues.getSelectedItem().toString();
            String securityAnswer = jTextFieldAnswer.getText();

            // Validate inputs
            if (username.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter username");
                return;
            }
            if (password.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter password");
                return;
            }
            if (!password.equals(confirmPassword)) {
                JOptionPane.showMessageDialog(this, "Passwords do not match");
                return;
            }
            if (securityAnswer.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter security answer");
                return;
            }

            // Register
            String registerResult = userManager.register(username, password, securityQuestion, securityAnswer);

            if (registerResult.equals("Registration successful")) {
                JOptionPane.showMessageDialog(this, "Registration successful!");
                // Return to login screen
                Login loginForm = new Login();
                loginForm.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, registerResult, "Registration Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            logger.log(Level.SEVERE, "Error during registration", e);
            JOptionPane.showMessageDialog(this, "An error occurred during registration");
        }
    }//GEN-LAST:event_jButtonCreateACCActionPerformed

    private void jLabelBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackMouseClicked
        Login loginForm = new Login();
        loginForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelBackMouseClicked

    private void jLabelBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackMouseEntered
        // TODO add your handling code here:
        jLabelBack.setForeground(new java.awt.Color(0,0,204));
    }//GEN-LAST:event_jLabelBackMouseEntered

    private void jLabelBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackMouseExited
        // TODO add your handling code here:
        jLabelBack.setForeground(new java.awt.Color(255,0,0));
    }//GEN-LAST:event_jLabelBackMouseExited

    private void jButtonCreateACCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCreateACCMouseEntered
        // TODO add your handling code here:
        jButtonCreateACC.setBackground(new java.awt.Color(102, 102, 255));
        jButtonCreateACC.setForeground(new java.awt.Color(0,0,204));
    }//GEN-LAST:event_jButtonCreateACCMouseEntered

    private void jButtonCreateACCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCreateACCMouseExited
        // TODO add your handling code here:
        jButtonCreateACC.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCreateACC.setForeground(new java.awt.Color(74,132,201));
    }//GEN-LAST:event_jButtonCreateACCMouseExited

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new Register().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconRichCat1;
    private javax.swing.JLabel iconRichCat2;
    private javax.swing.JButton jButtonCreateACC;
    private javax.swing.JComboBox<String> jComboBoxSecurityQues;
    private javax.swing.JLabel jLabelAnswer;
    private javax.swing.JLabel jLabelApp1;
    private javax.swing.JLabel jLabelBack;
    private javax.swing.JLabel jLabelConfirmPass;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelSecurityQues;
    private javax.swing.JLabel jLabelSignUp;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPasswordField jPasswordFieldConfirm;
    private javax.swing.JPasswordField jPasswordFieldCreate;
    private javax.swing.JTextField jTextFieldAnswer;
    private javax.swing.JTextField jTextFieldUserName;
    // End of variables declaration//GEN-END:variables
}
