/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * Transaction entry screen for Budget Buddy.
 * @author Kong Kar Shin
 * Responsibilities:
 * - Collect user input for a transaction
 * - Convert to TransactionData and send to TransactionManager
 * - Notify other screens (Dashboard/History) to refresh
 */
package gui;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;
import java.util.logging.Logger;
import model.TransactionData;
import model.Expense;
import model.Income;
import manager.TransactionManager;

public class Transaction extends javax.swing.JFrame {
    
    private static final Logger logger = Logger.getLogger(Transaction.class.getName());
    
    /**
     * Creates new form Transaction
     */
    public Transaction() {
        initComponents();
        pack(); // Make sure layout finishes calculating the size
        setLocationRelativeTo(null); // Center on screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelBack = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelCategory = new javax.swing.JLabel();
        jComboBoxCategory = new javax.swing.JComboBox<>();
        jLabelDate = new javax.swing.JLabel();
        jTextFieldDate = new javax.swing.JTextField();
        jLabelAmount = new javax.swing.JLabel();
        jTextFieldAmount = new javax.swing.JTextField();
        jLabelDescription = new javax.swing.JLabel();
        jScrollPaneDescBox = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonAddTransaction = new javax.swing.JButton();
        jLabelType = new javax.swing.JLabel();
        jComboBoxType = new javax.swing.JComboBox<>();
        jButtonReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(191, 229, 229));

        jLabelTitle.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(48, 136, 181));
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Transaction");
        jLabelTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img.backicons.png"))); // NOI18N
        jLabelBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBackMouseClicked(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(231, 242, 242));

        jLabelCategory.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabelCategory.setForeground(new java.awt.Color(48, 136, 181));
        jLabelCategory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCategory.setText("Category");
        jLabelCategory.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jComboBoxCategory.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jComboBoxCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Food", "Fashion", "Health", "Transport", "Salary", "Allowance", "Others" }));
        jComboBoxCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoryActionPerformed(evt);
            }
        });

        jLabelDate.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabelDate.setForeground(new java.awt.Color(48, 136, 181));
        jLabelDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDate.setText("Date");
        jLabelDate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTextFieldDate.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jTextFieldDate.setText("YYYY/MM/DD");
        jTextFieldDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDateActionPerformed(evt);
            }
        });

        jLabelAmount.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabelAmount.setForeground(new java.awt.Color(48, 136, 181));
        jLabelAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAmount.setText("Amount");
        jLabelAmount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTextFieldAmount.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jTextFieldAmount.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldAmount.setText("0.00");
        jTextFieldAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAmountActionPerformed(evt);
            }
        });

        jLabelDescription.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabelDescription.setForeground(new java.awt.Color(48, 136, 181));
        jLabelDescription.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDescription.setText("Description");
        jLabelDescription.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTextArea1.setColumns(10);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(4);
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setOpaque(false);
        jScrollPaneDescBox.setViewportView(jTextArea1);

        jButtonAddTransaction.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jButtonAddTransaction.setForeground(new java.awt.Color(48, 136, 181));
        jButtonAddTransaction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img.addicons.png"))); // NOI18N
        jButtonAddTransaction.setText("Add");
        jButtonAddTransaction.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonAddTransaction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAddTransactionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonAddTransactionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonAddTransactionMouseExited(evt);
            }
        });
        jButtonAddTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddTransactionActionPerformed(evt);
            }
        });

        jLabelType.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabelType.setForeground(new java.awt.Color(48, 136, 181));
        jLabelType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelType.setText("Type");
        jLabelType.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jComboBoxType.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jComboBoxType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Income", "Expense" }));
        jComboBoxType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTypeActionPerformed(evt);
            }
        });

        jButtonReset.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jButtonReset.setForeground(new java.awt.Color(48, 136, 181));
        jButtonReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img.reseticons.png"))); // NOI18N
        jButtonReset.setText("Reset");
        jButtonReset.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonResetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonResetMouseExited(evt);
            }
        });
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 27, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPaneDescBox, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabelType, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addComponent(jComboBoxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonAddTransaction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(160, 160, 160))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelType, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAmount)
                    .addComponent(jTextFieldAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneDescBox, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAddTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelBack)
                        .addGap(61, 61, 61)
                        .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelBack, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 1);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackMouseClicked
        Dashboard main = new Dashboard();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelBackMouseClicked

    private void jComboBoxCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCategoryActionPerformed

    private void jTextFieldDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDateActionPerformed

    private void jTextFieldAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAmountActionPerformed

    private void jButtonAddTransactionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddTransactionMouseClicked
        try {
            String type = jComboBoxType.getSelectedItem().toString();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy/MM/dd"); 
            LocalDate date = LocalDate.parse(jTextFieldDate.getText().trim(), formatter);
            double amount = TransactionManager.validateAmount(jTextFieldAmount.getText().trim());
            String category = jComboBoxCategory.getSelectedItem().toString();
            String description = jTextArea1.getText().trim();
            
            // Ensure that users cannot enter a date in the future
            LocalDate today = LocalDate.now();
            if (date.isAfter(today)) {
                JOptionPane.showMessageDialog(this, "Date cannot be in the future. Please enter a valid date up to today.");
                return;
            }

            // Create TransactionData and save it in TransactionManager (shared data)
            TransactionData transaction;
            if (type.equalsIgnoreCase("Income")) {
            transaction = new Income(date, amount, category, description);
            } else if (type.equalsIgnoreCase("Expense")) {
            transaction = new Expense(date, amount, category, description);
            } else {
            JOptionPane.showMessageDialog(this, "Invalid transaction type selected.");
            return;
            }
            TransactionManager.addTransaction(transaction);

            // Notify Dashboard and History (if they are open) to refresh
            Dashboard.refreshData();
            History.refreshData();
            
            JOptionPane.showMessageDialog(this, "Transaction added successfully!");

            // Reset form
            jTextFieldDate.setText("YYYY/MM/DD");
            jTextFieldAmount.setText("0.00");
            jTextArea1.setText("");
            jComboBoxType.setSelectedIndex(0);
            jComboBoxCategory.setSelectedIndex(0);
            
        } catch (IllegalArgumentException ex) { 
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Invalid Amount", JOptionPane.ERROR_MESSAGE);
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Invalid date format. Please use YYYY/MM/DD. Example: 2025/08/01", "Invalid Date", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAddTransactionMouseClicked

    private void jComboBoxTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTypeActionPerformed

    private void jButtonAddTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddTransactionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddTransactionActionPerformed

    private void jButtonResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonResetMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonResetMouseClicked

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        jTextFieldDate.setText("YYYY/MM/DD");
        // Clear the amount field
        jTextFieldAmount.setText("0.00");
        // Clear the description
        jTextArea1.setText("");
        // Reset type combo box to first item
        jComboBoxType.setSelectedIndex(0);
        // Reset type combo box to first Item
        jComboBoxCategory.setSelectedIndex(0);
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonAddTransactionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddTransactionMouseEntered
        // TODO add your handling code here:
        jButtonAddTransaction.setBackground(new java.awt.Color(102, 102, 255));
        jButtonAddTransaction.setForeground(new java.awt.Color(0,0,204));
    }//GEN-LAST:event_jButtonAddTransactionMouseEntered

    private void jButtonAddTransactionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddTransactionMouseExited
        // TODO add your handling code here:
        jButtonAddTransaction.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAddTransaction.setForeground(new java.awt.Color(74,132,201));
    }//GEN-LAST:event_jButtonAddTransactionMouseExited

    private void jButtonResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonResetMouseEntered
        // TODO add your handling code here:
        jButtonReset.setBackground(new java.awt.Color(102, 102, 255));
        jButtonReset.setForeground(new java.awt.Color(0,0,204));
    }//GEN-LAST:event_jButtonResetMouseEntered

    private void jButtonResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonResetMouseExited
        // TODO add your handling code here:
        jButtonReset.setBackground(new java.awt.Color(255, 255, 255));
        jButtonReset.setForeground(new java.awt.Color(74,132,201));
    }//GEN-LAST:event_jButtonResetMouseExited
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Transaction().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddTransaction;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JComboBox<String> jComboBoxCategory;
    private javax.swing.JComboBox<String> jComboBoxType;
    private javax.swing.JLabel jLabelAmount;
    private javax.swing.JLabel jLabelBack;
    private javax.swing.JLabel jLabelCategory;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelDescription;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelType;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneDescBox;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldAmount;
    private javax.swing.JTextField jTextFieldDate;
    // End of variables declaration//GEN-END:variables
}
